# Generated by Django 5.0.3 on 2024-03-30 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxy',
            old_name='user',
            new_name='owner',
        ),
    ]
